server:
  port: 8081

spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  data:
    web:
      pageable:
        one-indexed-parameters: true

termi:
  upload-dir: ${UPLOAD_DIR:./uploads}
  upload-base-url: ${UPLOAD_BASE_URL:http://localhost:8081/uploads}
