spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: sa
    url: jdbc:h2:file:./keycloak;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    context-path: /auth
    username: admin
    password: admin
    context-redirect: true
